/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlJuego;
import javax.swing.JOptionPane;
import modelo.RegistroJuego;
import modelo.RegistroUsuario;
import modelo.Usuario;

/**
 *
 * @author francisco
 */
public class GUIJuego extends javax.swing.JFrame {

    /**
     * Creates new form GUIJuego
     */
    public GUIJuego(Usuario usuario, RegistroJuego registroJuego, RegistroUsuario registroUsuario, boolean esNuevo) {
        initComponents();
        ControlJuego controlJuego = new ControlJuego(this, panelJuego1, panelInfo2, registroJuego, esNuevo);
        this.setLocationRelativeTo(null);
        this.panelInfo2.cargarUsuario(registroUsuario, usuario);
        this.panelInfo2.listenPanel(controlJuego);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego1 = new vista.PanelJuego();
        panelInfo2 = new vista.PnlInfoJuego();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GUIJuego"); // NOI18N
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJuego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelInfo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJuego1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PnlInfoJuego panelInfo2;
    private vista.PanelJuego panelJuego1;
    // End of variables declaration//GEN-END:variables

    public static int mensaje(String mensaje, int tipoMensaje, int iconoMensaje) {
        switch (tipoMensaje) {
            case 0:
                JOptionPane.showMessageDialog(null, mensaje, null, iconoMensaje);
                break;
            case 1:
                return JOptionPane.showConfirmDialog(null, mensaje, null, JOptionPane.YES_NO_OPTION);
        }
        return -1;
    }
}
