/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.util.ArrayList;
import modelo.Jugador;
import modelo.Tortuga;

/**
 *
 * @author vini
 */
public class PanelJuego extends javax.swing.JPanel {

    private Jugador jugador;
    private ArrayList<Tortuga> tortugas;

    /**
     * Creates new form PanelJuego1
     */
    public PanelJuego() {
        initComponents();
    }

    public void paint(Graphics g) {
        super.paint(g);
        jugador.pintarPersonaje(g);
        for (int i = 0; i < tortugas.size(); i++) {
            tortugas.get(i).pintarPersonaje(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

    public void setTortuga(ArrayList<Tortuga> tortugas) {
        this.tortugas = tortugas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
