/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlJuego;
import java.awt.Graphics;
import java.sql.Time;
import javax.swing.JLabel;

/**
 *
 * @author francisco
 */
public class PnlInfoJuego extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfoJuego
     */
    public PnlInfoJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Cargar = new javax.swing.JButton();
        jButton_Nueva = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Usuario = new javax.swing.JLabel();
        jLabel_UltimasPartidas = new javax.swing.JLabel();
        jButton_Guardar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        jButton_Cargar.setText("Cargar partida");

        jButton_Nueva.setText("Nueva partida");

        jLabel7.setText("Tiempo:");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Ultimas partidas:");

        jLabel_Usuario.setText("USUARIO");

        jLabel_UltimasPartidas.setText("0:00");

        jButton_Guardar.setText("Guardar partida");

        jButton_Salir.setText("Salir del juego");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel_Usuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_UltimasPartidas))
                    .addComponent(jButton_Guardar)
                    .addComponent(jButton_Cargar)
                    .addComponent(jButton_Nueva)
                    .addComponent(jLabel7)
                    .addComponent(jButton_Salir))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_Usuario))
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_UltimasPartidas))
                .addGap(18, 18, 18)
                .addComponent(jButton_Guardar)
                .addGap(18, 18, 18)
                .addComponent(jButton_Cargar)
                .addGap(18, 18, 18)
                .addComponent(jButton_Nueva)
                .addGap(18, 18, 18)
                .addComponent(jButton_Salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cargar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_Nueva;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_UltimasPartidas;
    private javax.swing.JLabel jLabel_Usuario;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_CARGAR = "Cargar partida";
    public static final String BTN_GUARDAR = "Guardar partida";
    public static final String BTN_NUEVA = "Nueva partida";
    public static final String BTN_SALIR = "Salir del juego";

    public void escuchar(ControlJuego controlJuego) {
        this.jButton_Cargar.addActionListener(controlJuego);
        this.jButton_Guardar.addActionListener(controlJuego);
        this.jButton_Nueva.addActionListener(controlJuego);
        this.jButton_Salir.addActionListener(controlJuego);
    }

    public String getjLabel_Usuario() {
        return jLabel_Usuario.getText().trim();
    }

    public void setjLabel_Usuario(String jLabel_Usuario) {
        this.jLabel_Usuario.setText(jLabel_Usuario);
    }

    public String getjLabel_UltimasPartidas() {
        return jLabel_UltimasPartidas.getText();
    }

    public void setjLabel_UltimasPartidas(String jLabel_UltimasPartidas) {
        this.jLabel_UltimasPartidas.setText(jLabel_UltimasPartidas);
    }

}
